### ISSUE TITLE
How to set up a server 

### ISSUE THREAD

**Issue by hithere145235** [CloneTrooper1019/Roblox_0.3.368.0#27] opened 2021-03-17 01:43 UTC
I want to start an online server so I can invite some of my friends to play but I don't know how to start a server

**Comment by CloneTrooper1019** [comment] 2021-03-17 02:28
Duplicate of https://github.com/CloneTrooper1019/Roblox_0.3.368.0/issues/23

**Closed by CloneTrooper1019** 2021-03-17 02:28 UTC
